syntax = "proto3";

import "google/protobuf/empty.proto";

package proto;
We expect the KV store server to provide the following basic APIs to its clients:

service KVStore {
    rpc Put(KVPair) returns Status {}
    rpc Swap(KVPair) returns Value {}
    rpc Get(Key) returns Value {}
    rpc Scan(ScanRange) returns List[KVPair] {}
    rpc Delete(key) returns Status {}
}

message KVPair {
    string key = 1;
    string value = 2;
}

message Key {
    string key = 1;
}

message Value {
    string value = 1;
}

message Status {
    bool success = 1;
}